# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Lottitle(models.Model):
    lotdt_idx = models.BigIntegerField(primary_key=True)
    lotname = models.CharField(max_length=255)
    device = models.CharField(max_length=255)
    tester = models.IntegerField(blank=True, null=True)
    col_1_h = models.FloatField(blank=True, null=True)
    col_1_l = models.FloatField(blank=True, null=True)
    col_2_h = models.FloatField(blank=True, null=True)
    col_2_l = models.FloatField(blank=True, null=True)
    col_3_h = models.FloatField(blank=True, null=True)
    col_3_l = models.FloatField(blank=True, null=True)
    col_4_h = models.FloatField(blank=True, null=True)
    col_4_l = models.FloatField(blank=True, null=True)
    col_5_h = models.FloatField(blank=True, null=True)
    col_5_l = models.FloatField(blank=True, null=True)
    col_6_h = models.FloatField(blank=True, null=True)
    col_6_l = models.FloatField(blank=True, null=True)
    col_7_h = models.FloatField(blank=True, null=True)
    col_7_l = models.FloatField(blank=True, null=True)
    col_8_h = models.FloatField(blank=True, null=True)
    col_8_l = models.FloatField(blank=True, null=True)
    col_9_h = models.FloatField(blank=True, null=True)
    col_9_l = models.FloatField(blank=True, null=True)
    col_10_h = models.FloatField(blank=True, null=True)
    col_10_l = models.FloatField(blank=True, null=True)
    col_11_h = models.FloatField(blank=True, null=True)
    col_11_l = models.FloatField(blank=True, null=True)
    col_12_h = models.FloatField(blank=True, null=True)
    col_12_l = models.FloatField(blank=True, null=True)
    col_13_h = models.FloatField(blank=True, null=True)
    col_13_l = models.FloatField(blank=True, null=True)
    col_14_h = models.FloatField(blank=True, null=True)
    col_14_l = models.FloatField(blank=True, null=True)
    col_15_h = models.FloatField(blank=True, null=True)
    col_15_l = models.FloatField(blank=True, null=True)
    col_16_h = models.FloatField(blank=True, null=True)
    col_16_l = models.FloatField(blank=True, null=True)
    col_17_h = models.FloatField(blank=True, null=True)
    col_17_l = models.FloatField(blank=True, null=True)
    col_18_h = models.FloatField(blank=True, null=True)
    col_18_l = models.FloatField(blank=True, null=True)
    col_19_h = models.FloatField(blank=True, null=True)
    col_19_l = models.FloatField(blank=True, null=True)
    col_20_h = models.FloatField(blank=True, null=True)
    col_20_l = models.FloatField(blank=True, null=True)
    col_21_h = models.FloatField(blank=True, null=True)
    col_21_l = models.FloatField(blank=True, null=True)
    col_22_h = models.FloatField(blank=True, null=True)
    col_22_l = models.FloatField(blank=True, null=True)
    col_23_h = models.FloatField(blank=True, null=True)
    col_23_l = models.FloatField(blank=True, null=True)
    col_24_h = models.FloatField(blank=True, null=True)
    col_24_l = models.FloatField(blank=True, null=True)
    col_25_h = models.FloatField(blank=True, null=True)
    col_25_l = models.FloatField(blank=True, null=True)
    col_26_h = models.FloatField(blank=True, null=True)
    col_26_l = models.FloatField(blank=True, null=True)
    col_27_h = models.FloatField(blank=True, null=True)
    col_27_l = models.FloatField(blank=True, null=True)
    col_28_h = models.FloatField(blank=True, null=True)
    col_28_l = models.FloatField(blank=True, null=True)
    col_29_h = models.FloatField(blank=True, null=True)
    col_29_l = models.FloatField(blank=True, null=True)
    col_30_h = models.FloatField(blank=True, null=True)
    col_30_l = models.FloatField(blank=True, null=True)
    col_31_h = models.FloatField(blank=True, null=True)
    col_31_l = models.FloatField(blank=True, null=True)
    col_32_h = models.FloatField(blank=True, null=True)
    col_32_l = models.FloatField(blank=True, null=True)
    col_33_h = models.FloatField(blank=True, null=True)
    col_33_l = models.FloatField(blank=True, null=True)
    col_34_h = models.FloatField(blank=True, null=True)
    col_34_l = models.FloatField(blank=True, null=True)
    col_35_h = models.FloatField(blank=True, null=True)
    col_35_l = models.FloatField(blank=True, null=True)
    col_36_h = models.FloatField(blank=True, null=True)
    col_36_l = models.FloatField(blank=True, null=True)
    col_37_h = models.FloatField(blank=True, null=True)
    col_37_l = models.FloatField(blank=True, null=True)
    col_38_h = models.FloatField(blank=True, null=True)
    col_38_l = models.FloatField(blank=True, null=True)
    col_39_h = models.FloatField(blank=True, null=True)
    col_39_l = models.FloatField(blank=True, null=True)
    col_40_h = models.FloatField(blank=True, null=True)
    col_40_l = models.FloatField(blank=True, null=True)
    col_41_h = models.FloatField(blank=True, null=True)
    col_41_l = models.FloatField(blank=True, null=True)
    col_42_h = models.FloatField(blank=True, null=True)
    col_42_l = models.FloatField(blank=True, null=True)
    col_43_h = models.FloatField(blank=True, null=True)
    col_43_l = models.FloatField(blank=True, null=True)
    col_44_h = models.FloatField(blank=True, null=True)
    col_44_l = models.FloatField(blank=True, null=True)
    col_45_h = models.FloatField(blank=True, null=True)
    col_45_l = models.FloatField(blank=True, null=True)
    col_46_h = models.FloatField(blank=True, null=True)
    col_46_l = models.FloatField(blank=True, null=True)
    col_47_h = models.FloatField(blank=True, null=True)
    col_47_l = models.FloatField(blank=True, null=True)
    col_48_h = models.FloatField(blank=True, null=True)
    col_48_l = models.FloatField(blank=True, null=True)
    col_49_h = models.FloatField(blank=True, null=True)
    col_49_l = models.FloatField(blank=True, null=True)
    col_50_h = models.FloatField(blank=True, null=True)
    col_50_l = models.FloatField(blank=True, null=True)
    col_51_h = models.FloatField(blank=True, null=True)
    col_51_l = models.FloatField(blank=True, null=True)
    col_52_h = models.FloatField(blank=True, null=True)
    col_52_l = models.FloatField(blank=True, null=True)
    col_53_h = models.FloatField(blank=True, null=True)
    col_53_l = models.FloatField(blank=True, null=True)
    col_54_h = models.FloatField(blank=True, null=True)
    col_54_l = models.FloatField(blank=True, null=True)
    col_55_h = models.FloatField(blank=True, null=True)
    col_55_l = models.FloatField(blank=True, null=True)
    col_56_h = models.FloatField(blank=True, null=True)
    col_56_l = models.FloatField(blank=True, null=True)
    col_57_h = models.FloatField(blank=True, null=True)
    col_57_l = models.FloatField(blank=True, null=True)
    col_58_h = models.FloatField(blank=True, null=True)
    col_58_l = models.FloatField(blank=True, null=True)
    col_59_h = models.FloatField(blank=True, null=True)
    col_59_l = models.FloatField(blank=True, null=True)
    col_60_h = models.FloatField(blank=True, null=True)
    col_60_l = models.FloatField(blank=True, null=True)
    col_61_h = models.FloatField(blank=True, null=True)
    col_61_l = models.FloatField(blank=True, null=True)
    col_62_h = models.FloatField(blank=True, null=True)
    col_62_l = models.FloatField(blank=True, null=True)
    col_63_h = models.FloatField(blank=True, null=True)
    col_63_l = models.FloatField(blank=True, null=True)
    col_64_h = models.FloatField(blank=True, null=True)
    col_64_l = models.FloatField(blank=True, null=True)
    col_65_h = models.FloatField(blank=True, null=True)
    col_65_l = models.FloatField(blank=True, null=True)
    col_66_h = models.FloatField(blank=True, null=True)
    col_66_l = models.FloatField(blank=True, null=True)
    col_67_h = models.FloatField(blank=True, null=True)
    col_67_l = models.FloatField(blank=True, null=True)
    col_68_h = models.FloatField(blank=True, null=True)
    col_68_l = models.FloatField(blank=True, null=True)
    col_69_h = models.FloatField(blank=True, null=True)
    col_69_l = models.FloatField(blank=True, null=True)
    col_70_h = models.FloatField(blank=True, null=True)
    col_70_l = models.FloatField(blank=True, null=True)
    col_71_h = models.FloatField(blank=True, null=True)
    col_71_l = models.FloatField(blank=True, null=True)
    col_72_h = models.FloatField(blank=True, null=True)
    col_72_l = models.FloatField(blank=True, null=True)
    col_73_h = models.FloatField(blank=True, null=True)
    col_73_l = models.FloatField(blank=True, null=True)
    col_74_h = models.FloatField(blank=True, null=True)
    col_74_l = models.FloatField(blank=True, null=True)
    col_75_h = models.FloatField(blank=True, null=True)
    col_75_l = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'LotTitle'


class Testdata(models.Model):
    idx = models.AutoField(primary_key=True)
    lotdt_idx = models.ForeignKey(Lottitle, models.DO_NOTHING, db_column='lotdt_idx')
    t_result = models.ForeignKey('Testresult', models.DO_NOTHING, db_column='t_result')
    col_1 = models.FloatField(blank=True, null=True)
    col_2 = models.FloatField(blank=True, null=True)
    col_3 = models.FloatField(blank=True, null=True)
    col_4 = models.FloatField(blank=True, null=True)
    col_5 = models.FloatField(blank=True, null=True)
    col_6 = models.FloatField(blank=True, null=True)
    col_7 = models.FloatField(blank=True, null=True)
    col_8 = models.FloatField(blank=True, null=True)
    col_9 = models.FloatField(blank=True, null=True)
    col_10 = models.FloatField(blank=True, null=True)
    col_11 = models.FloatField(blank=True, null=True)
    col_12 = models.FloatField(blank=True, null=True)
    col_13 = models.FloatField(blank=True, null=True)
    col_14 = models.FloatField(blank=True, null=True)
    col_15 = models.FloatField(blank=True, null=True)
    col_16 = models.FloatField(blank=True, null=True)
    col_17 = models.FloatField(blank=True, null=True)
    col_18 = models.FloatField(blank=True, null=True)
    col_19 = models.FloatField(blank=True, null=True)
    col_20 = models.FloatField(blank=True, null=True)
    col_21 = models.FloatField(blank=True, null=True)
    col_22 = models.FloatField(blank=True, null=True)
    col_23 = models.FloatField(blank=True, null=True)
    col_24 = models.FloatField(blank=True, null=True)
    col_25 = models.FloatField(blank=True, null=True)
    col_26 = models.FloatField(blank=True, null=True)
    col_27 = models.FloatField(blank=True, null=True)
    col_28 = models.FloatField(blank=True, null=True)
    col_29 = models.FloatField(blank=True, null=True)
    col_30 = models.FloatField(blank=True, null=True)
    col_31 = models.FloatField(blank=True, null=True)
    col_32 = models.FloatField(blank=True, null=True)
    col_33 = models.FloatField(blank=True, null=True)
    col_34 = models.FloatField(blank=True, null=True)
    col_35 = models.FloatField(blank=True, null=True)
    col_36 = models.FloatField(blank=True, null=True)
    col_37 = models.FloatField(blank=True, null=True)
    col_38 = models.FloatField(blank=True, null=True)
    col_39 = models.FloatField(blank=True, null=True)
    col_40 = models.FloatField(blank=True, null=True)
    col_41 = models.FloatField(blank=True, null=True)
    col_42 = models.FloatField(blank=True, null=True)
    col_43 = models.FloatField(blank=True, null=True)
    col_44 = models.FloatField(blank=True, null=True)
    col_45 = models.FloatField(blank=True, null=True)
    col_46 = models.FloatField(blank=True, null=True)
    col_47 = models.FloatField(blank=True, null=True)
    col_48 = models.FloatField(blank=True, null=True)
    col_49 = models.FloatField(blank=True, null=True)
    col_50 = models.FloatField(blank=True, null=True)
    col_51 = models.FloatField(blank=True, null=True)
    col_52 = models.FloatField(blank=True, null=True)
    col_53 = models.FloatField(blank=True, null=True)
    col_54 = models.FloatField(blank=True, null=True)
    col_55 = models.FloatField(blank=True, null=True)
    col_56 = models.FloatField(blank=True, null=True)
    col_57 = models.FloatField(blank=True, null=True)
    col_58 = models.FloatField(blank=True, null=True)
    col_59 = models.FloatField(blank=True, null=True)
    col_60 = models.FloatField(blank=True, null=True)
    col_61 = models.FloatField(blank=True, null=True)
    col_62 = models.FloatField(blank=True, null=True)
    col_63 = models.FloatField(blank=True, null=True)
    col_64 = models.FloatField(blank=True, null=True)
    col_65 = models.FloatField(blank=True, null=True)
    col_66 = models.FloatField(blank=True, null=True)
    col_67 = models.FloatField(blank=True, null=True)
    col_68 = models.FloatField(blank=True, null=True)
    col_69 = models.FloatField(blank=True, null=True)
    col_70 = models.FloatField(blank=True, null=True)
    col_71 = models.FloatField(blank=True, null=True)
    col_72 = models.FloatField(blank=True, null=True)
    col_73 = models.FloatField(blank=True, null=True)
    col_74 = models.FloatField(blank=True, null=True)
    col_75 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'TestData'


class Testresult(models.Model):
    id = models.IntegerField(primary_key=True)
    descript = models.CharField(db_column='Descript', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'TestResult'


class Testunit(models.Model):
    col = models.IntegerField(primary_key=True)
    unit = models.CharField(max_length=255)
    name = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'TestUnit'
